config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :favorites
  resources :items
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  delete '/favorites/:id', to: 'favorites#destroy', as: 'unfavor'
  post '/favorites/new', to: 'favorites#add_favorite', as: 'add_favorite'
  delete '/favorites/:id', to: 'home#destroy', as: 'unfavor_remove'
  post '/transactions/new', to: 'transactions#new_transaction', as: "add_transaction"
  get 'search' , to: 'home#search'

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :user_id, uniqueness: {scope: :item_id, message: "This item is already in your Favorites!"}
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all
    @user_favorites = Favorite.where(user_id: current_user.id)
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @favorite, notice: 'Favorite was successfully created.' }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to :root, notice: 'Favorite removed' }
      format.json { head :no_content }
    end
  end


  def add_favorite
    @favorite = Favorite.create(user_id: params[:user_id], item_id: params[:item_id])

    redirect_to :root
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favorite_params
      params.require(:favorite).permit(:user_id, :item_id)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_with(model: favorite, local: true) do |form| %>
  <% if favorite.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h4>

      <ul>
        <% favorite.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.text_field :item_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<div class="card px-4">
<h1>Favorites:</h1>

<%if @user_favorites != nil && !@user_favorites.empty?%>
  <%@user_favorites.each do |favorite| %>
    <%item = favorite.item%>
      <div class="card">
        <div class="row no-gutters">
            <div class="col-auto">
               <%if item.photo.attached?%>
                <%=image_tag(item.photo, size: '300x200')%>
                <%else%>
                <%= image_tag("https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fproperty.berkeley.edu%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fpanopoly_image_original%2Fpublic%2FIcon_Items_For_Sale.png%3Fitok%3DV_rIMLoE&f=1&nofb=1", size: '300x200') %> 
                <% end %>
            </div>
            <div class="col">
                <div class="card-block px-2"><br>
                    <h3 class="card-title"><%= item.title %></h3>
                    <h4 class="card-number">$<%= item.price %></h4>
                    <p class="card-text">Description: <%=item.description%></p>
                     <div class="btn-group">
                <%= button_to "View", item_path(item), method: :get, :class => "btn btn-primary mr-2 rounded"%>
                <%= button_to "Unfavor", unfavor_path(favorite), method: :delete ,class: "btn btn-danger mr-2 rounded"%>

                <%= link_to "Buy", new_transaction_path(:item_id => item.id),:class => "btn btn-success mr-2 rounded"%>
                </div>
                </div>
            </div>
        </div>
        <div class="card-footer w-100 text-muted">
            <%= item.category%>, <%= item.user.location%>
        </div>
        </div><br>
      <% end %>
      <%else%>
      <h5> You haven't liked anything yet! </h5>  
<% end %>
</div>

app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favorite.user_id %>
</p>

<p>
  <strong>Items:</strong>
  <%= @favorite.item_id %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>