config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :favorites
  resources :items
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  delete '/favorites/:id', to: 'favorites#destroy', as: 'unfavor'
  post '/favorites/new', to: 'favorites#add_favorite', as: 'add_favorite'
  delete '/favorites/:id', to: 'home#destroy', as: 'unfavor_remove'
  post '/transactions/new', to: 'transactions#new_transaction', as: "add_transaction"
  get 'search' , to: 'home#search'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @items = Item.where.not(user_id: current_user.id)
        bought_items = Transaction.all.map {|trans| trans.item}
        @items -= bought_items
    end


    def search

        @item = Item.where("title LIKE ?", "%" + params[:q] + "%")

        
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">MarketPlace</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: 'nav-link'%>
        </li>
        <%if !user_signed_in?%>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
       <%else%> 
            <li class="nav-item">
            <%= link_to "My Items", items_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to  "Sell Item", new_item_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Favorites" , favorites_path, class:"nav-link"  %>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
            Account  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
  <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
  <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
</svg>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to  "Edit Account",edit_user_registration_path , class:"dropdown-item" %>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </ul>
            </li>
        </ul>
      <form class="d-flex" action='/search'>
        <input class="form-control mr-2" type="search" placeholder="Search" aria-label="Search" name='q'>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <%end%>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<!doctype html>
<html lang="en">
<head>
</head>
<body>

<style>
h1 {color: white;}
</style>

<h1>MarketPlace</h1><br>

    <% if @items != nil%>
    <% @items.each do |item| %>
        
  <div class="card">
        <div class="row no-gutters">
            <div class="col-auto">
                <%if item.photo.attached?%>
                <%=image_tag(item.photo, size: '300x200')%>
                <%else%>
                <%= image_tag("https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fproperty.berkeley.edu%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fpanopoly_image_original%2Fpublic%2FIcon_Items_For_Sale.png%3Fitok%3DV_rIMLoE&f=1&nofb=1", size: '300x200') %> 
                <% end %>
            </div>
            <div class="col">
                <div class="card-block px-2"><br>
                    <h3 class="card-title"><%= item.title %></h3>
                    <h4 class="card-number">$<%= item.price %></h4>
                    <p class="card-text">Description: <%=item.description%></p>

                     <div class="btn-group">
                <%= button_to "View", item_path(item), method: :get, :class => "btn btn-primary mr-2 rounded"%>
            <%if Favorite.where(user_id: current_user.id, item_id: item.id) == [] %>
                <%= button_to "Favorite", add_favorite_path, method: :post ,:class => "btn btn-primary mr-2 rounded", params: { user_id: current_user.id ,item_id: item.id }%>
            <% else %>
                <%= button_to "Unfavor", unfavor_path(Favorite.where(user_id: current_user.id, item_id: item.id).ids), method: :delete ,class: "btn btn-danger mr-2 rounded"%>
            <% end %>
                <%= link_to "Buy", new_transaction_path(:item_id => item.id), class: "btn btn-success mr-2 rounded"%>
                </div>
                </div>
            </div>
        </div>
        <div class="card-footer w-100 text-muted">
            <%= item.category%>, <%= item.user.location%>
        </div>
        </div>
        <br>
       <%end%>
    <%end%>
</body>
</html>

app/views/home/search.html.erb
<%%>

<h1> Search query </h1>

<section>
  <div class="container">
    <div class="card">
      <div class="row">
        <div class="col-md-6">
          <div class="card-block px-4"><br>
            <h4 class="card-title"><%= @item[0].title%></h4>
            <p class="card-text">Description: <%= @item[0].description%></p>
            <p class="card-text">Seller Name: <%= @item[0].user.first_name%></p>
            <p class="card-text">Seller Contact: <%= @item[0].user.email%></p>
            <p class="card-text">Location: <%= @item[0].user.location %></small></p>
            
                    <div class="btn-group">
                  <% if @item[0].user_id == current_user.id %>
                      <%= link_to 'Back', items_path ,class: "btn btn-primary mr-2 rounded" %>
                      <%= link_to 'Edit', edit_item_path(@item[0]), class: "btn btn-primary mr-2 rounded"%>
                  <%elsif Transaction.all.find_by(item_id: @item[0].id)%>
                      <%= link_to 'Back', root_path ,class: "btn btn-primary mr-2 rounded" %>
                  <%else%>
                      <%= button_to "Favorite", add_favorite_path, method: :post ,:class => "btn btn-primary mr-2 rounded", params: { user_id: current_user.id ,item_id: @item[0].id }%><br>
                      <%= link_to 'Back', root_path ,class: "btn btn-primary mr-2 rounded" %>
                      <%= link_to "Buy", new_transaction_path(:item_id => @item[0].id), class: "btn btn-success mr-2 rounded"%>
                  <%end%>
              </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="card-img-bottom ">
                    <%if @item[0].photo.attached?%>
                    <%=image_tag(@item[0].photo, size: '623x420')%>
                    <%else%>
                    <%= image_tag("https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fproperty.berkeley.edu%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fpanopoly_image_original%2Fpublic%2FIcon_Items_For_Sale.png%3Fitok%3DV_rIMLoE&f=1&nofb=1", size: '623x420') %> 
                    <% end %>
          </div>
        </div>
      </div>
     <div class="card-footer w-100 text-muted">
            MarketPlace 2020
        </div>
    </div>
  </div>
</section>