config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :favorites
  resources :items
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  delete '/favorites/:id', to: 'favorites#destroy', as: 'unfavor'
  post '/favorites/new', to: 'favorites#add_favorite', as: 'add_favorite'
  delete '/favorites/:id', to: 'home#destroy', as: 'unfavor_remove'
  post '/transactions/new', to: 'transactions#new_transaction', as: "add_transaction"
  get 'search' , to: 'home#search'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @item = Item.find(params[:id])
  end
  

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    
    @item = Item.find(params[:item_id])
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @item = Item.find(params[:transaction][:item_id])
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to :root, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new}
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_transaction
    @transaction = Transaction.new
    @transaction = Transaction.create(user_id: params[:user_id], item_id: params[:item_id], review: params[:review],rating: params[:rating])

    redirect_to :root
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:user_id, :review, :rating, :item_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h4>

      <ul>
        <% transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.text_field :item_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Review</th>
      <th>Rating</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.user_id %></td>
        <td><%= transaction.review %></td>
        <td><%= transaction.rating %></td>
        <td><%= transaction.item_id %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<style>
.review-form-group {
  margin-left: 18%;
  text-align: center;
  width: 126%;
  font-size: 20px
}
</style>

<div class="card px-4"><br>
<% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% @transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<section>
    <div class="card">
      <div class="row">
        <div class="col-md-6">
          <div class="card-block px-4"><br>
            <h4 class="card-title"><%= @item.title%></h4>
            <p class="card-text">Description: <%= @item.description%></p>
            <p class="card-text">Seller Name: <%= @item.user.first_name%></p>
            <p class="card-text">Seller Contact: <%= @item.user.email%></p>
            <p class="card-text">Location: <%= @item.user.location %></small></p>
              </div>
            </div>
            <div class="col-md-6">
              <div class="card-img-bottom ">
                    <%if @item.photo.attached?%>
                    <%=image_tag(@item.photo, size: '610x420')%>
                    <%else%>
                    <%= image_tag("https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fproperty.berkeley.edu%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fpanopoly_image_original%2Fpublic%2FIcon_Items_For_Sale.png%3Fitok%3DV_rIMLoE&f=1&nofb=1", size: '610x420') %> 
                    <% end %>
          </div>
        </div>
      </div>
    </div>
</section><br>

<div class="card px-4"><br>
 <div style="text-align: center;">

<h2> Review Your Experience: </h2>
<%= form_for @transaction do |f| %>
<div class="review-form-group"><br>
  <%= f.text_area :review, class: "form-control", placeholder: "Write a review for this item and a seller"%>
</div>
  <div class="review-form-group"><br>
  <%= f.number_field :rating, in: 1.0..5.0, step: 0.5 , class: "form-control", placeholder: "Rate this seller (0 - 5)"%>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id%>
  <%= f.hidden_field :item_id, value: @item.id%>
<br / >
<div class="span2">
  <%= link_to 'Back', items_path ,class: "btn btn-primary btn-block" %>
  <%= f.submit "Mark as Sold" , class: "btn btn-success btn-block", params: {id: @item.id}%>
<% end %>
</div>
<br>

<div id="smart-button-container">
      <div style="text-align: center;">
        <div id="paypal-button-container"></div>
      </div>
    </div>
  <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD" data-sdk-integration-source="button-factory"></script>
  <script>
    function initPayPalButton() {
      paypal.Buttons({
        style: {
          shape: 'rect',
          color: 'blue',
          layout: 'vertical',
          label: 'paypal',
          
        },

        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{"amount":{"currency_code":"USD","value":1}}]
          });
        },

        onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
            alert('Transaction completed by ' + details.payer.name.given_name + '!');
          });
        },

        onError: function(err) {
          console.log(err);
        }
      }).render('#paypal-button-container');
    }
    initPayPalButton();
  </script>
</div>
<br>

</div>
</div>
</div>